version: '3.7'

services:
  aise-api:
    container_name: aise-api
    build: ./app
    command: sh -c "/code/app/scripts/run_app.sh"
    restart: unless-stopped
    environment:
      APP_PROJECT_NAME: ${APP_PROJECT_NAME}
      AUDIO_RATE: ${AUDIO_RATE}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
    volumes:
      - ./app/system-static/speechbrain:/code/app/system-static/speechbrain

  aise-client:
    container_name: aise-client
    build: ./client
    command: sh -c "/code/client/run_client.sh"
    restart: unless-stopped
    environment:
      API_RECOGNITION_URI: "http://aise-api:9000/api/recognize/"
      API_ENHANCEMENT_URI: "http://aise-api:9000/api/enhancement/"
      API_SEPARATION_URI: "http://aise-api:9000/api/separate/"
      AUDIO_RATE: ${AUDIO_RATE}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}

  aise-nginx:
    image: nginx:1.23.2
    container_name: aise-nginx
    restart: unless-stopped
    volumes:
      - ./configs/${STAND_CONFIG_FOLDER}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/${STAND_CONFIG_FOLDER}/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - aise-api
      - aise-client

networks:
  default:
    driver: bridge
